services:
  postgres:
    image: postgres:17.2
    container_name: teletext-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - teletext-net

  backend:
    build:
      context: .
      dockerfile: docker-files/java/Dockerfile
    container_name: teletext-backend
    env_file:
      - .env.webclient
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - APP_PORT=${BACKEND_PORT}
      - SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
      - TELETEXT_JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_ISSUER=${JWT_ISSUER}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - TELETEXT_ADMIN_LOGIN_URL=${TELETEXT_ADMIN_LOGIN_URL}
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./docker-files/java/.m2:/root/.m2
      - ./docker-files/java/logs:/app/logs
    networks:
      - teletext-net
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: docker-files/frontend/Dockerfile
    container_name: teletext-frontend
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - teletext-net
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  teletext-net:
    driver: bridge